### ISSUE TITLE
Github Actions to auto publish npm package

### ISSUE THREAD

**Issue by munanadi** [coral-xyz/anchor#1019]
Shouldn't we write a Github action to take care of pushing the npm anchor thing automatically? Like say parse a commit tag and if it says some version run like `0.18.2` that should trigger and push it to npm.

It could solve one part of 
![image](https://user-images.githubusercontent.com/22261173/141696897-74403d40-2524-4c58-9eb6-7521815bc4ec.png)

lol :stuck_out_tongue: 

The action config file can look something like this. Not sure if this will work though. Never done this before. Need to double-check.
Thoughts on the whole actions thing though?

```yml
name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  programs:
    runs-on: ubuntu-latest
    name: Build and publish the SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn build
      - name: Publish
        run: yarn publish ./ts/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
```
