### ISSUE TITLE
More options for local validator in `anchor test`

### ISSUE THREAD

**Issue by ndrewtl** [coral-xyz/anchor#2082]
I've been developing on Anchor for awhile, and I wanted to know if it would be possible to configure the local validator that runs for testing. For example, I would like to import other programs using the `--bpf-program` option or external accounts using `--clone` and `--account`. I see in the source code that some options are automatically passed in, such as the names of all programs to deploy. However, it would be great if we could add the ability to pass in arbitrary arguments as well. I'm envisioning something like:
```sh
$ anchor test --skip-deploy -- --bpf-program <ADDRESS> <FILE>
```

**Comment by callensm** [comment]
programs can be added be creating a `[[test.genesis]]` block for each in your `Anchor.toml` file:

```toml
[[test.genesis]]
address = "<public key>"
program = "<relative path to .so>"
```

and cloning account data can be done with:

```toml
[[test.validator.clone]]
address = "<public key>"
```
