### ISSUE TITLE
Running `anchor new` doesn't work when `[[test.genesis]]` is included

### ISSUE THREAD

**Issue by metaproph3t** [coral-xyz/anchor#2584]
I'm managing working with multiple program across repos via the `[[test.genesis]]` method espoused on the website and by contributors in the Discord.

This is what my Anchor.toml looks like:
```toml
[features]
seeds = false
skip-lint = false
[programs.localnet]
autocrat = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
conditional_program = "2zJ3FQgeYhw1bEgTE7UeTrgZXhwXavYEbbPKtf4BNMta"

[[test.genesis]]
address = "22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD"
program = "clob.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/autocrat.ts"
```

This works fine, except whenever I run `anchor new` with this setup I get the following error:

```
thread 'main' panicked at 'Must be well formed: ValueAfterTable', cli/src/config.rs:595:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I remove the `[[test.genesis]]` and the two lines below it, `anchor new` succeeds
