### ISSUE TITLE
`provider.wallet` includes the user's home path instead of `~`

### ISSUE THREAD

**Issue by acheroncrypto** [coral-xyz/anchor#2695]
### Problem

Initializing a new workspace with `anchor init` or adding a new program with `anchor new` saves the full `provider.wallet` path:

```toml
[provider]
wallet = "/home/user/.config/solana/id.json"
```

It should instead use `~` for reproducability:

```toml
[provider]
wallet = "~/.config/solana/id.json"
```

**Comment by macaujack** [comment]
Hi. This issue still exists on my machine. My system is macOS 14.1. Anchor version is 0.29.0. Solana version is 1.18.2

**Comment by acheroncrypto** [comment]
This was fixed in https://github.com/coral-xyz/anchor/pull/2696 but it's not yet released.

You can use this fix by including the commit hash like the following:

```toml
[toolchain]
anchor_version = "0.29.0-9cb8d0355dcf0df53a2195dbc17e7565fd29325b"
```

or install the latest CLI from GitHub:

```
cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
```
