### ISSUE TITLE
Unable to run multiple commands with `anchor test`.

### ISSUE THREAD

**Issue by dhruvja** [coral-xyz/anchor#2771]
I have tests in typescript as well as in rust, so i wanted to run both `cargo test` and `yarn ts-mocha ... `. So i tried to add both the commands in the `scripts` section under `test` tag in `anchor.toml` file like below.
```toml
[scripts]
test = "cargo test --lib -- --nocapture --include-ignored ::anchor; yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```
I get the following error
```
Unrecognized option: 'p'
```
Both the commands when ran seperately work but when they are together seperated by either `;` or `&&`, they dont seem to work. 

When i tried to run the above command in terminal it worked, but i want to make it work with `anchor test` since it starts and closes the local validator automatically during the process.

**Comment by acheroncrypto** [comment]
Scripts currently accept a single program, therefore anything after `cargo` is passed as an argument to the `cargo` command.

As a workaround, you can create `test.sh` that you want to execute and add:

```toml
[scripts]
test = "sh test.sh"
```

in your `Anchor.toml` to execute the script with `anchor test`.
