### ISSUE TITLE
`anchor keys sync` change Anchor.toml [provider] unexpected

### ISSUE THREAD

**Issue by xG0Ian** [coral-xyz/anchor#3388]
when use custom rpc:
```toml
[provider]
cluster = "https://rpc.ankr.com/solana_devnet"
wallet = "~/.config/solana/id.json"
```
and run: 
1. `rm target/deploy/*-keypair.json`
2. `anchor keys sync`

Anchor.toml will be changed to:
```toml
[provider]
cluster = ["https://rpc.ankr.com/solana_devnet", "wss://rpc.ankr.com/solana_devnet"]
wallet = "~/.config/solana/id.json"
```
and we will get this error from `anchor keys sync`:
```
Workspace configuration error: Unable to deserialize config: TOML parse error at line 14, column 11
   |
14 | cluster = ["https://rpc.ankr.com/solana_devnet", "wss://rpc.ankr.com/solana_devnet"]
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
invalid type: sequence, expected string or map
```
