### ISSUE TITLE
Anchor IDL generation does not work with feature flags

### ISSUE THREAD

**Issue by gwalen** [coral-xyz/anchor#3465]
**Issue**:  
When using feature flags in a Rust file to set the program ID, which should be reflected in the IDL file, passing feature flags during compilation does not work as expected. Instead, only the default option specified in `Cargo.toml` is applied.

**Code Example**:  
Here is an example of code where the program ID depends on feature flags:  
```rust
cfg_if! {
    if #[cfg(feature = "mainnet")] {
        declare_id!("worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth");
    } else if #[cfg(feature = "devnet")] {
        declare_id!("3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5");
    }
}

#[derive(Debug, Clone)]
pub struct Wormhole;

impl Id for Wormhole {
    fn id() -> Pubkey {
        ID
    }
}
```

**Build Command**:  
```bash
anchor build --arch sbf -- --features $(NETWORK) --no-default-features
```

**Result**:  
IDL generation only considers the default settings specified in `Cargo.toml`, regardless of which feature flag is passed.

**Workaround**:  
To generate an IDL for a specific environment, you must manually change the default feature in `Cargo.toml` each time before compilation.

Cargo.toml example:  
```toml
[features]
default = ["mainnet"]
# Uncomment the desired environment before building
# default = ["testnet"]
# default = ["devnet"]
```

**Comment by acheroncrypto** [comment]
This has been implemented in https://github.com/coral-xyz/anchor/pull/3059 and mentioned in the (unpublished) v0.31.0 (https://github.com/coral-xyz/anchor/pull/3259) release notes:

https://github.com/acheroncrypto/anchor/blob/v0.31.0/docs/src/pages/release-notes/0.31.0.md#pass-cargo-args-to-idl-build

Unfortunately, we don't yet have a release that includes this feature, but you can install CLI from any commit starting from `ca7fcee` to make it work.

You can also make the CLI consistent for all people if you specify it in `Anchor.toml`:

```toml
[toolchain]
anchor_version = "0.30.1-ca7fcee6b8269b732b66536f72ff3fb48cf1b5f9"
```

Thanks for the report, but since this issue is essentially the same as https://github.com/coral-xyz/anchor/issues/3054, I'm closing it as completed, but feel free to reopen it if the problem continues.
